/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tp1.java;

import java.math.BigInteger;
import java.util.*;

public class App {

    public static BigInteger Fibonacci(int n) {
    //Resolvemos utilizando programacion dinamica
        BigInteger fib1 = BigInteger.ONE;   // Valor de Fibonacci para n-1
        BigInteger fib2 = BigInteger.ONE;   // Valor de Fibonacci para n-2
        BigInteger fibN = BigInteger.ZERO;  // Valor de Fibonacci para n
        
        for (int i = 2; i <= n; i++) {
            fibN = fib1.add(fib2);
            fib2 = fib1;
            fib1 = fibN;
        }
        
        return fibN;
    }

    public static String encontrarPalabraMasUsada (String texto, int N){
        // Convertimos el texto a minusculas y lo dividimos en palabras
        String[] palabras = texto.toLowerCase().split("[^a-zA-Z]+");
        
        // Creamos un mapa para realizar un seguimiento del recuento de palabras
        Map<String, Integer> contadorPalabras = new HashMap<>(); //La clave es cada palabra que cumple con el requisito de longitud minima
        
        // Contamos la ocurrencia de cada palabra
        for (String palabra : palabras) {
            if (palabra.length() >= N) {
                contadorPalabras.put(palabra, contadorPalabras.getOrDefault(palabra, 0) + 1);
            }
        }
        
        // Buscamos en el mapa la palabra más usada
        String palabraMasUsada = "";
        int maxCant = 0;
        
        for (Map.Entry<String, Integer> par : contadorPalabras.entrySet()) {
            if (par.getValue() > maxCant) {
                palabraMasUsada = par.getKey();
                maxCant = par.getValue();
            }
        }
        
        return palabraMasUsada;
    }

    public static void main(String[] args) {
        String text = "Hello world hello Java java hello World";
        int n = 4;
        
        String palabraMasUsada = encontrarPalabraMasUsada(text, n);
        
        System.out.println("La palabra mas usada es: " + palabraMasUsada);

        int nro = 90;

        System.out.println("El Fibonacci de " + nro + " es " + Fibonacci(nro));

    }

    public Object getGreeting() {
        return null;
    }

}